{{- if or .Values.secrets.databaseUrl .Values.secrets.redisUrl .Values.secrets.jwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vibecast.fullname" . }}-secrets
  labels:
    {{- include "vibecast.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.databaseUrl }}
  database-url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.redisUrl }}
  redis-url: {{ .Values.secrets.redisUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- end }}
{{- end }}